name: QA Training CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
      - name: Run Tests
      run: npm test

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      if: always() # لضمان رفع التقرير حتى لو فشلت الاختبارات
      with:
        name: test-results-report
        path: junit.xml
